Create a new data

In [23]:

import pandas as pd

df = pd.DataFrame([
    ['hot', 'sunny', 'yes'],
    ['mild', 'overcast', 'yes'],
    ['cool', 'rainy', 'no']])
df.columns = ['temp', 'weather', 'play']
df

temp   weather play
0   hot     sunny  yes
1  mild  overcast  yes
2  cool     rainy   no

Mapping

In [12]:
weather_mapping = {
    'sunny' : 2,
    'overcast' : 1,
    'rainy' : 0}
df['weather'] = df['weather'].map(weather_mapping)
df

temp  weather play
0   hot        2  yes
1  mild        1  yes
2  cool        0   no

Encoding labels

In [13]:
import numpy as np

weather_mapping = {label: idx for idx, label in
                  enumerate(np.unique(df['play']))}
print(weather_mapping)

{'yes': 1, 'no': 0}


Transform the class labels into integers

In [14]:
df['play'] = df['play'].map(weather_mapping)
print(df)

   temp  weather  play
0   hot        2     1
1  mild        1     1
2  cool        0     0


Reverse in the mapping dictionary

In [15]:
inv_class_mapping = {v: k for k, v in weather_mapping.items()}
df['play'] = df['play'].map(inv_class_mapping)
print(df)

   temp  weather play
0   hot        2  yes
1  mild        1  yes
2  cool        0   no


Label Encoder

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

weather_encoded = le.fit_transform(df['weather'].values)
print(weather_encoded)

[2 1 0]


Inverse transform

In [17]:
temp_encoded=le.fit_transform(df['temp'].values)
print(temp_encoded)

[1 2 0]


In [18]:
label=le.fit_transform(df['play'].values)
print(label)

[1 1 0]


Features

In [19]:
features=list(zip(weather_encoded,temp_encoded))

KNN clasifier model. Import the KNeighborsClassifier module

In [20]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors = 3)

model.fit(features, label)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

Predict Output

In [21]:
predicted= model.predict([[0,2]])   # 0 : Overcast, 2 : Mild
print(predicted)

[1]
