Import Libraries

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

Load Dataset

In [12]:
col_names = ['mpg_double', 'cylinders_int', 'displacement_double', 'horsepower_double', 'weight_double',
             'acceleration_double', 'model_int', 'origin_cat']

car = pd.read_csv("cars_auto.csv", header=None, names=col_names)

car.head()

mpg_double  cylinders_int  displacement_double  horsepower_double  \
0          18              8                  307                130   
1          15              8                  350                165   
2          18              8                  318                150   
3          16              8                  304                150   
4          17              8                  302                140   

   weight_double  acceleration_double  model_int origin_cat  
0           3504                 12.0         70        US0  
1           3693                 11.5         70        US0  
2           3436                 11.0         70        US0  
3           3433                 12.0         70        US0  
4           3449                 10.5         70        US0

Explatory Data Analysis

In [13]:
car.shape

(406, 8)

Data Preprocessing

In [14]:
X = car.drop('origin_cat', axis = 1)
y = car['origin_cat']

Model Selection

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

Support Vector Machine Classifier Model

In [16]:
from sklearn.svm import SVC
svclassifier = SVC(kernel = 'linear')
svclassifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

Predictions

In [17]:
y_pred = svclassifier.predict(X_test)


Evaluating the algorithm

In [18]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[10  0  4  2]
 [ 0  0  1  0]
 [ 8  0  6  4]
 [ 0  0  6 41]]
              precision    recall  f1-score   support

     Europe1       0.56      0.62      0.59        16
      Japan1       0.00      0.00      0.00         1
      Japan2       0.35      0.33      0.34        18
         US0       0.87      0.87      0.87        47

   micro avg       0.70      0.70      0.70        82
   macro avg       0.45      0.46      0.45        82
weighted avg       0.69      0.70      0.69        82



/usr/local/lib/python3.5/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
